### ISSUE TITLE
[FEATURE] Expanding shuttles is weird on planets

### ISSUE THREAD

**Issue by checkraisefold** [voidcrew/Voidcrew-LRP#246]
### Additional Info: 
If you expand a shuttle on a planet, you can't expand it with the shuttle expansion permit because it's a "restricted area". However, if you use the "create new area" button next to the skills/crafting buttons, THEN use the shuttle expansion permit, it allows you to expand the area. I feel like there is some unintentional behavior here. If you can't create an area in a restricted one with the permit, then you shouldn't be able to do so with the button.

**Comment by SuperNovaa41** [comment]
I haven't found this to be the case, you have to have everything completely enclosed, else it will say it's a restricted area.

**Comment by checkraisefold** [comment]
I tried even when completely closed, said it was a restricted area. Airlocks, walls, and floors. Had to use the "create new area" button instead of the blueprints, which actually worked. Blueprints only said restricted area until I used the button.

**Comment by Sealed101** [comment]
last time i checked it was because the shuttle permit additionally checks whether the area has NOTELEPORT or not while the hud button doesnt. novaa might not have been getting the issue because of adminrank or something? since i am getting the same issue as well, having to use the hud button then the permit over the new area
